repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=100]
    exclude: ^data/
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
    exclude: ^.github/actions/forestreet-setup/
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    exclude: ^.github/actions/forestreet-setup/
- repo: https://github.com/pycqa/isort
  rev: 6.0.0
  hooks:
  - id: isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.6
  hooks:
    # Run the linter.
  - id: ruff
    types_or: [python, pyi]
    args: [--fix]
    # Run the formatter.
  - id: ruff-format
    types_or: [python, pyi]
- repo: local
  hooks:
  - id: pytest
    name: Run pytest on repo
    entry: bash -c 'pytest'
    language: system
